<CENTER>
<H1><!--SITENAME--></H1><P>
<H2>Subscriptions Available</H2>

<UL>
	<!--BEGIN SUBSCRIPTIONS-->
	<LI><A HREF="subscription.php?id=<!--SUBSCRIPTIONS.IDENTITY-->"><!--SUBSCRIPTIONS.IDENTITY--></A> - <!--SUBSCRIPTIONS.TITLE--> (<!--SUBSCRIPTIONS.CATEGORY-->)</LI>
	<!--END SUBSCRIPTIONS-->
</UL>
</CENTER>
